// angular/story-204-angular/src/app/components/task-create/task-create.component.ts
import { Component, input, output } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

import { TaskType } from '../../interfaces/task-type.interface';

@Component({
  selector: 'task-create',
  imports: [ReactiveFormsModule],
  templateUrl: './task-create.component.html',
  styleUrl: './task-create.component.css'
})
export class TaskCreate {
  nextId = input<number>(0);
  onCreate = output<TaskType>();

  task = <TaskType>({ id: null, name: '', priority: 0, status: 0 });

  name = new FormControl('');
  priority = new FormControl<number>(0);
  status = new FormControl<number>(0);

  resetTask() {
    this.task.id = null;
    this.task.name = '';
    this.name.setValue('');
  }

  handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') this.handleCreateClick();
  }

  handleCreateClick() {
    this.task.id = this.nextId();
    this.task.name = this.name.value || '';
    this.task.priority = this.priority.value || 0;
    this.task.status = this.status.value || 0;
    this.onCreate.emit({ ...this.task });
    this.resetTask();
  }
}

<div class="task-create">
  <input placeholder="Enter a task" [formControl]="name" (keydown)="handleKeyDown($event)" autofocus />
  <select [formControl]="priority">
    <option [ngValue]="0">Low</option>
    <option [ngValue]="1">Normal</option>
    <option [ngValue]="2">High</option>
    <option [ngValue]="3">Urgent</option>
  </select>
  <select [formControl]="status">
    <option [ngValue]="0">Todo</option>
    <option [ngValue]="1">Doing</option>
    <option [ngValue]="2">Done</option>
  </select>
  <button (click)="handleCreateClick()">Create</button>
</div>

// story-003-react/src/components/TaskCreate.jsx
import { useRef, useState } from 'react';
import './TaskCreate.css';

export default function TaskCreate({ nextId, onCreate }) {
  const [task, setTask] = useState({ id: null, name: '', priority: 0, status: 0 });
  const lastSelRef = useRef({ priority: 0, status: 0 });

  function resetTask() {
    setTask({ id: null, name: '', ...lastSelRef.current });
  }

  function handleSubmit(e) {
    e.preventDefault();
    const name = task.name.trim();
    if (!name) return;

    onCreate({
      id: nextId,
      name,
      priority: Number(task.priority),
      status: Number(task.status),
    });

    lastSelRef.current = {
      priority: Number(task.priority),
      status: Number(task.status),
    };

    resetTask();
  }

  return (
    <form className="taskcreate" onSubmit={handleSubmit}>
      <input
        placeholder="Enter a task"
        value={task.name}
        onChange={e => setTask({ ...task, name: e.target.value })}
        onKeyDown={e => { if (e.key === 'Enter') handleSubmit(e); }}
        autoFocus
      />
      <select
        value={task.priority}
        onChange={e => setTask({ ...task, priority: Number(e.target.value) })}
      >
        <option value={0}>Low</option>
        <option value={1}>Normal</option>
        <option value={2}>High</option>
        <option value={3}>Urgent</option>
      </select>
      <select
        value={task.status}
        onChange={e => setTask({ ...task, status: Number(e.target.value) })}
      >
        <option value={0}>Todo</option>
        <option value={1}>Doing</option>
        <option value={2}>Done</option>
      </select>
      <button type="submit" disabled={!task.name.trim()}>Create</button>
    </form>
  );
}
