// vue/story-104-vue/src/components/TaskEdit.vue
<script setup>
import { ref } from 'vue';
import { PRIORITY_VALUES, STATUS_VALUES } from '@/helpers/labels';

const props = defineProps(['tasks', 'id']);
const emit = defineEmits(['onUpdate', 'onCancel']);

const task = ref({ ...props.tasks.find(t => t.id === props.id) });

function handleKeyDown(e) {
  if (e.keyCode === 13) handleUpdateClick();
  if (e.keyCode === 27) emit('onCancel');
}

function handleUpdateClick(e) {
  emit('onUpdate', {
    id: task.value.id,
    name: task.value.name,
    priority: task.value.priority,
    status: task.value.status,
  });
}
</script>

<template>
  <div class="taskedit">
    <input placeholder="Enter a task" v-model="task.name" @keydown="handleKeyDown" autofocus />
    <select v-model="task.priority">
      <option v-for="item in PRIORITY_VALUES" :value="item.value">{{ item.label }}</option>
    </select>
    <select v-model="task.status">
      <option v-for="item in STATUS_VALUES" :value="item.value">{{ item.label }}</option>
    </select>      
    <button @click="handleUpdateClick">Update</button>
    <button @click="$emit('onCancel')">Cancel</button>
  </div>
</template>

<style scoped>
.taskedit {
  margin-bottom: 16px;
  padding: 20px;
  border: solid 1px #ccc;
}
</style>

// story-003-react/src/components/TaskEdit.jsx
import { useState } from 'react';
import { STATUS_VALUES, PRIORITY_VALUES } from '../helpers/labels';

import './TaskEdit.css';

export default function TaskEdit({ tasks, id, onUpdate, onCancel }) {
  const [task, setTask] = useState({ ...tasks.find(t => t.id === id) });

  function handleKeyDown(e) {
    if (e.key === 'Enter') handleUpdateClick();
    if (e.key === 'Escape') onCancel();
  }

  function handleUpdateClick() {
    onUpdate({
      id: task.id,
      name: task.name,
      priority: parseInt(task.priority),
      status: parseInt(task.status),
    });
  }

  return (
    <div className="TaskEdit">
      <input placeholder="Enter a task" value={task.name} onKeyDown={handleKeyDown}
        onChange={e => setTask({...task, name: e.target.value})} autoFocus />
      <select value={task.priority} onChange={e => setTask({...task, priority: parseInt(e.target.value)})}>
        {PRIORITY_VALUES.map(v => <option value={v.value}>{v.label}</option>)}
      </select>
      <select value={task.status} onChange={e => setTask({...task, status: parseInt(e.target.value)})}>
        {STATUS_VALUES.map(v => <option value={v.value}>{v.label}</option>)}
      </select>
      <button onClick={handleUpdateClick}>Update</button>
      <button onClick={onCancel}>Cancel</button>
    </div>
  );
}
