// angular/story-204-angular/src/app/components/task-list/task-list.component.ts
import { Component, signal, input, output } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

import { TaskType } from '../../interfaces/task-type.interface';
import { FilterType } from '../../interfaces/filter-type.interface';
import { PriorityLabelPipe } from '../../pipes/priority-label.pipe';
import { StatusLabelPipe } from '../../pipes/status-label.pipe';
import { TaskEdit } from '../task-edit/task-edit.component';

@Component({
  selector: 'task-list',
  imports: [ReactiveFormsModule, PriorityLabelPipe, StatusLabelPipe, TaskEdit],
  templateUrl: './task-list.component.html',
  styleUrl: './task-list.component.css'
})
export class TaskList {
  tasks = input<TaskType[]>([]);
  onUpdate = output<TaskType>();
  onDelete = output<number | null>();
  onSort= output<string>();
  onFilter = output<FilterType>();

  editId: number | null = null;
  priorityFilter = new FormControl<number>(-1);
  statusFilter = new FormControl<number>(-1);
  sortedTasks = <TaskType[]>[];

  handleEditClick(id: number | null) {
    this.editId = id;
  }

  handleUpdateClick(task: TaskType) {
    this.onUpdate.emit(task);
    this.editId = null;
  }

  handleDeleteClick(id: number | null) {
    this.onDelete.emit(id);
  }

  handleCancelClick() {
    this.editId = null;
  }

  handleSortingClick(property: string) {
    this.onSort.emit(property);
  }

  handleFilter() {
    this.onFilter.emit({
      status: this.statusFilter.value || 0,
      priority: this.priorityFilter.value || 0,
    });
  }
}

<div class="task-list">
  <div class="body">
    <table>
      <thead>
        <tr>
          <th (click)="handleSortingClick('id')">ID</th>
          <th (click)="handleSortingClick('name')">Task</th>
          <th (click)="handleSortingClick('priority')">Priority</th>
          <th (click)="handleSortingClick('status')">Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        @for (t of tasks(); track t.id) {
          <tr>
            @if (t.id === editId) {
              <td colspan="5" class="edit">
                <task-edit [task]="t" (onUpdate)="handleUpdateClick($event)" (onCancel)="handleCancelClick()" />
              </td>
            } @else {
              <td>{{ t.id }}</td>
              <td>{{ t.name }}</td>
              <td>{{ t.priority | priorityLabel }}</td>
              <td>{{ t.status | statusLabel }}</td>
              <td>
                <button (click)="handleEditClick(t.id)">Edit</button>
                <button (click)="handleDeleteClick(t.id)">Delete</button>
              </td>
            }
          </tr>
        }
      </tbody>
    </table>
  </div>
  <div class="footer">
    <select [formControl]="priorityFilter" (change)="handleFilter()">
      <option [ngValue]="-1">All Priorities</option>
      <option [ngValue]="0">Low</option>
      <option [ngValue]="1">Normal</option>
      <option [ngValue]="2">High</option>
      <option [ngValue]="3">Urgent</option>
    </select>
    <select [formControl]="statusFilter" (change)="handleFilter()">
      <option [ngValue]="-1">All Statuses</option>
      <option [ngValue]="0">Todo</option>
      <option [ngValue]="1">Doing</option>
      <option [ngValue]="2">Done</option>
    </select>
  </div>
</div>

// story-003-react/src/components/TaskList.jsx
import { useState } from 'react';

import TaskEdit from './TaskEdit';
import { getStatusLabel, getPriorityLabel } from '../helpers/labels';

import './TaskList.css';

export default function TaskList({ tasks, onUpdate, onDelete, onSort, onFilter }) {
  const [priorityFilter, setPriorityFilter] = useState(-1);
  const [statusFilter, setStatusFilter] = useState(-1);
  const [editId, setEditId] = useState(null);

  function handleEditClick(id) {
    setEditId(id);
  }

  function handleUpdateClick(task) {
    onUpdate(task);
    setEditId(null);
  }

  function handleCancelClick() {
    setEditId(null);
  }

  function handleSortingClick(property) {
    const sorted = [...tasks];

    switch (property) {
      case 'id':
        sorted.sort((a, b) => a.id - b.id);
        break;
      case 'name':
        sorted.sort((a, b) => a.name.localeCompare(b.name));
        break;
      case 'priority':
        sorted.sort((a, b) => a.priority - b.priority);
        break;a.name > b.name
      case 'status':
        sorted.sort((a, b) => a.status - b.status);
        break;
    }

    onSort(sorted);
  }

  function handlePriorityFilter(priority) {
    priority = parseInt(priority);
    setPriorityFilter(priority);
    onFilter(priority, statusFilter);
  }

  function handleStatusFilter(status) {
    status = parseInt(status);
    setStatusFilter(status);
    onFilter(priorityFilter, status);
  }

  return (
    <div className="tasklist">
      <div className="body">
        <table>
          <thead>
            <tr>
              <th onClick={() => handleSortingClick('id')}>ID</th>
              <th onClick={() => handleSortingClick('name')}>Task</th>
              <th onClick={() => handleSortingClick('priority')}>Priority</th>
              <th onClick={() => handleSortingClick('status')}>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          {tasks.map((t) => editId === t.id ?
            <tr key={t.id}>
              <td colSpan="5" className="edit">
                <TaskEdit tasks={tasks} id={editId} onUpdate={handleUpdateClick} onCancel={handleCancelClick} />
              </td>
            </tr> :
            <tr key={t.id}>
              <td>{t.id}</td>
              <td>{t.name}</td>
              <td>{getPriorityLabel(t.priority)}</td>
              <td>{getStatusLabel(t.status)}</td>
              <td>
                <button onClick={() => handleEditClick(t.id)}>Edit</button>
                <button onClick={() => onDelete(t.id)}>Delete</button>
              </td>
            </tr>
          )}
          </tbody>
        </table>
      </div>
      <div className="footer">
        <select value={priorityFilter} onChange={(e) => handlePriorityFilter(e.target.value)}>
          <option value="-1">All Priorities</option>
          <option value="0">Low</option>
          <option value="1">Normal</option>
          <option value="2">High</option>
          <option value="3">Urgent</option>
        </select>
        <select value={statusFilter} onChange={(e) => handleStatusFilter(e.target.value)}>
          <option value="-1">All Statuses</option>
          <option value="0">Todo</option>
          <option value="1">Doing</option>
          <option value="2">Done</option>
        </select>
      </div>
    </div>
  );
}
