// vue/story-004-vue/src/components/TaskCreate.vue
<script setup>
import { ref } from 'vue';
import { PRIORITY_VALUES, STATUS_VALUES } from '@/helpers/labels';

const props = defineProps(['nextId']);
const emit = defineEmits(['onCreate']);

const defaultTask = { id: null, name: '', priority: 0, status: 0 };
const task = ref(defaultTask);

function resetTask() {
  defaultTask.name = '';
  defaultTask.priority = task.value.priority;
  defaultTask.status = task.value.status;
  task.value = { ...defaultTask };
}

function handleKeyDown(e) {
  if (e.key === 'Enter') handleCreateClick();
}

function handleCreateClick(e) {
  emit('onCreate', { ...task.value, id: props.nextId });
  resetTask();
}
</script>

<template>
  <div class="taskcreate">
    <input placeholder="Enter a task" v-model="task.name" @keydown="handleKeyDown" autofocus />
    <select v-model="task.priority">
      <option v-for="item in PRIORITY_VALUES" :value="item.value">{{ item.label }}</option>
    </select>
    <select v-model="task.status">
      <option v-for="item in STATUS_VALUES" :value="item.value">{{ item.label }}</option>
    </select>      
    <button @click="handleCreateClick">Create</button>
  </div>
</template>

<style scoped>
.taskcreate {
  margin-bottom: 16px;
  padding: 20px;
  border: solid 1px #ccc;
  text-align: center;
}
</style>

// react/story-003-react/src/components/TaskCreate.jsx
import { useRef, useState } from 'react';
import { STATUS_VALUES, PRIORITY_VALUES } from '../helpers/labels';

import './TaskCreate.css';

export default function TaskCreate({ nextId, onCreate }) {
  const [task, setTask] = useState({ id: null, name: '', priority: 0, status: 0 });
  const lastSelRef = useRef({ priority: 0, status: 0 });

  function resetTask() {
    setTask({ id: null, name: '', ...lastSelRef.current });
  }

  function handleSubmit(e) {
    e.preventDefault();
    const name = task.name.trim();
    if (!name) return;

    onCreate({
      id: nextId,
      name,
      priority: Number(task.priority),
      status: Number(task.status),
    });

    lastSelRef.current = {
      priority: Number(task.priority),
      status: Number(task.status),
    };

    resetTask();
  }

  return (
    <form className="TaskCreate" onSubmit={handleSubmit}>
      <input
        placeholder="Enter a task"
        value={task.name}
        onChange={e => setTask({ ...task, name: e.target.value })}
        onKeyDown={e => { if (e.key === 'Enter') handleSubmit(e); }}
        autoFocus
      />
      <select
        value={task.priority}
        onChange={e => setTask({ ...task, priority: Number(e.target.value) })}
      >
        {PRIORITY_VALUES.map(v => <option value={v.value}>{v.label}</option>)}
      </select>
      <select
        value={task.status}
        onChange={e => setTask({ ...task, status: Number(e.target.value) })}
      >
        {STATUS_VALUES.map(v => <option value={v.value}>{v.label}</option>)}
      </select>
      <button type="submit" disabled={!task.name.trim()}>Create</button>
    </form>
  );
}
