// vue/story-001-vue/src/components/TaskApp.vue
<script setup>
import { useTemplateRef, onMounted, ref } from 'vue'

const tasks = ref([])
const task = ref(null)
const name = ref('')
const inputRef = useTemplateRef('inputRef')

let nextId = 0

onMounted(() => {
  inputRef.value.focus()
})

function handleKeyDown(e) {
  if (e.key === 'Enter') handleUpdateClick()
  if (e.key === 'Escape') handleEditClick()
}

function handleUpdateClick(e) {
  if (task.value === null) {
    const newTask = {
        id: nextId++,
        name: name.value.trim(),
        status: 'Todo',
        priority: 'Normal',
      }
    tasks.value = [...tasks.value, newTask]
  } else { 
    const index = tasks.value.findIndex(t => t.id == task.value.id)
    task.value.name = name.value        
    tasks.value.splice(index, 1, task.value)       
    task.value = null
  }

  name.value = ''
}

function handleEditClick(id = null) {
  if (task.value === null && id !== null) {
    const found = tasks.value.find(t => t.id == id)
    task.value = found
    name.value = found?.name ?? null
  } else {
    task.value = null
    name.value = ''
  }

  inputRef.value.focus();
}

function handleDeleteClick(id) {
  tasks.value = tasks.value.filter(t => t.id !== id)
}
</script>

<template>
  <div class="TaskApp">
    <div class="head">
      <input class="task" placeholder="Enter a task" ref="inputRef" v-model="name" @keydown="handleKeyDown" autofocus />
      <button @click="handleUpdateClick">{{ task === null ? 'Create' : 'Update' }}</button>
    </div>
    <div class="body">
      <ol>
        <li v-for="t in tasks" :key="t.id">
          <span class="task">{{ t.name }}</span>
          <button @click="handleEditClick(t.id)">{{ task?.id === t.id ? 'Cancel' : 'Edit' }}</button>
          <button @click="handleDeleteClick(t.id)">Delete</button>
        </li>
      </ol>
    </div>
  </div>
</template>

<style scoped>
.TaskApp {
  margin: 0;
  padding: 20px;
  border: solid 1px #ccc;
}

.head {
  text-align: center;
}

.task {
  display: inline-block;
  width: 250px;
}
</style>

// angular/story-201-angular/src/app/components/task-app/task-app.component.ts
import { inject, Component, ElementRef } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

interface TaskType {
  id: number;
  name: string | null;
}

@Component({
  selector: 'task-app',
  imports: [ReactiveFormsModule],
  templateUrl: './task-app.component.html',
  styleUrl: './task-app.component.css'
})
export class TaskApp {
  nextId = 0;

  tasks = <TaskType[]>[];
  task = <TaskType | null>(null);

  inputRef = <ElementRef | null> null;
  name = new FormControl('');

  constructor() {
    this.inputRef = inject(ElementRef);
  }

  onKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') this.onUpdateClick();
    if (e.key === 'Escape') this.onEditClick();
  }

  onUpdateClick() {
    if (this.task === null) {
      this.tasks.push({
        id: this.nextId,
        name: this.name.value,
      });

      this.nextId++;
    } else {
      const index = this.tasks.findIndex(t => t.id === this.task?.id);
      this.task.name = this.name.value;
      this.tasks.splice(index, 1, this.task);
      this.task = null;
    }

    this.name.setValue('');
  }

  onEditClick(id: number | null = null) {
    if (this.task === null && id !== null) {
      const found = this.tasks.find(t => t.id === id);
      this.task = found || null;
      this.name.setValue(found?.name ?? null);
    } else {
      this.task = null;
      this.name.setValue('');
    }

    this.inputRef?.nativeElement.querySelector('#inputRef')?.focus();
  }

  onDeleteClick(id: number) {
    this.tasks = this.tasks.filter(t => t.id !== id)
  }
}

<div class="task-app">
  <div class="head">
    <input id="inputRef" class="task" placeholder="Enter a task" type="text" [formControl]="name"
      (keydown)="onKeyDown($event)" autofocus />
    <button (click)="onUpdateClick()">@if (task === null) { Create } @else { Update }</button>
  </div>
  <div class="body">
    <ol>
      @for (t of tasks; track t.id) {
        <li>
          <span class="task">{{ t.name }}</span>
          <button (click)="onEditClick(t.id)">@if (task?.id === t.id) { Cancel } @else { Edit }</button>
          <button (click)="onDeleteClick(t.id)">Delete</button>
        </li>
      }
    </ol>
  </div>
</div>
