// vue/story-104-vue/src/components/TaskList.vue

<script setup>
import { ref, computed } from 'vue'
import TaskEdit from './TaskEdit.vue'
import { getPriorityLabel, getStatusLabel, PRIORITY_VALUES, STATUS_VALUES } from '@/helpers/labels'

const props = defineProps({
  tasks: { type: Array, required: true }
})
const emit = defineEmits(['onUpdate','onDelete','onSort','onFilter'])

const editingId = ref(null)
const priorityFilter = ref(-1)
const statusFilter = ref(-1)

const byId = computed(()=>{
  const m = new Map()
  for (const t of props.tasks) m.set(t.id, t)
  return m
})

function startEdit(id){ editingId.value = id }
function cancelEdit(){ editingId.value = null }
function saveEdit(task){ emit('onUpdate', task); editingId.value = null }
function deleteRow(id){ if (editingId.value === id) editingId.value = null; emit('onDelete', id) }

function sortBy(col){ emit('onSort', col) }
function applyFilters(){ emit('onFilter', Number(priorityFilter.value), Number(statusFilter.value)) }
</script>

<template>
  <div class="tasklist">
    <div class="filters">
      <select v-model.number="priorityFilter" @change="applyFilters" aria-label="Filter by priority">
        <option :value="-1">All Priorities</option>
        <option v-for="p in PRIORITY_VALUES" :key="p.value" :value="p.value">{{ p.label }}</option>
      </select>
      <select v-model.number="statusFilter" @change="applyFilters" aria-label="Filter by status">
        <option :value="-1">All Statuses</option>
        <option v-for="s in STATUS_VALUES" :key="s.value" :value="s.value">{{ s.label }}</option>
      </select>
    </div>

    <table>
      <thead>
        <tr>
          <th @click="sortBy('id')">ID</th>
          <th @click="sortBy('name')">Task</th>
          <th @click="sortBy('priority')">Priority</th>
          <th @click="sortBy('status')">Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="t in props.tasks" :key="t.id">
          <td>{{ t.id }}</td>

          <td v-if="editingId !== t.id">{{ t.name }}</td>
          <td v-else colspan="3" class="edit-cell">
            <TaskEdit :task="byId.get(t.id)" @onSave="saveEdit" @onCancel="cancelEdit" />
          </td>

          <template v-if="editingId !== t.id">
            <td>{{ getPriorityLabel(t.priority) }}</td>
            <td>{{ getStatusLabel(t.status) }}</td>
          </template>

          <td class="actions">
            <button v-if="editingId !== t.id" @click="startEdit(t.id)">Edit</button>
            <button v-else @click="cancelEdit">Cancel</button>
            <button @click="deleteRow(t.id)">Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style scoped>
.tasklist { margin-top: 8px; }
.filters {
  display: flex;
  gap: 12px;
  align-items: center;
  justify-content: flex-end;
  margin-bottom: 8px;
  flex-wrap: wrap;
}
table { width: 100%; border-collapse: collapse; }
thead { background: #eee; }
th, td { padding: 8px; border-bottom: 1px solid #eee; }
th { cursor: pointer; user-select: none; }
.actions { white-space: nowrap; }
.edit-cell { padding: 0; }
</style>

// react/story-004-typescript/src/components/TaskList.tsx
import { useState } from 'react';

import TaskEdit from './TaskEdit';
import { getStatusLabel, getPriorityLabel, STATUS_VALUES, PRIORITY_VALUES } from '../helpers/labels';
import type { TaskListProps, Task, PriorityFilter, StatusFilter} from '../types/types';

import './TaskList.css';

export default function TaskList({ tasks, onUpdate, onDelete, onSort, onFilter }: TaskListProps) {
  const [priorityFilter, setPriorityFilter] = useState<PriorityFilter>(-1);
  const [statusFilter, setStatusFilter] = useState<StatusFilter>(-1);
  const [editId, setEditId] = useState<number | null>(null);

  function handleEditClick(id: number) {
    setEditId(id);
  }

  function handleUpdateClick(task: Task) {
    onUpdate(task);
    setEditId(null);
  }

  function handleCancelClick() {
    setEditId(null);
  }

  function handleSortingClick(property: keyof Task) {
    const sorted = [...tasks];

    switch (property) {
      case 'id': sorted.sort((a, b) => a.id - b.id); break;
      case 'name': sorted.sort((a, b) => a.name.localeCompare(b.name)); break;
      case 'priority': sorted.sort((a, b) => a.priority - b.priority); break;
      case 'status': sorted.sort((a, b) => a.status - b.status); break;
      default: break;
    }

    onSort(sorted);
  }

  function handlePriorityFilter(priority: number) {
    priority = Number(priority) ;
    setPriorityFilter(priority as PriorityFilter);
    onFilter(priority as PriorityFilter, statusFilter as StatusFilter);
  }

  function handleStatusFilter(status: number) {
    status = Number(status);
    setStatusFilter(status as StatusFilter);
    onFilter(priorityFilter as PriorityFilter, status as StatusFilter);
  }

  return (
    <div className="TaskList">
      <div className="body">
        <table>
          <thead>
            <tr>
              <th onClick={() => handleSortingClick('id')}>ID</th>
              <th onClick={() => handleSortingClick('name')}>Task</th>
              <th onClick={() => handleSortingClick('priority')}>Priority</th>
              <th onClick={() => handleSortingClick('status')}>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          {tasks.map((t) => editId === t.id ?
            <tr key={t.id}>
              <td colSpan={5} className="edit">
                <TaskEdit tasks={tasks} id={editId} onUpdate={handleUpdateClick} onCancel={handleCancelClick} />
              </td>
            </tr> :
            <tr key={t.id}>
              <td>{t.id}</td>
              <td>{t.name}</td>
              <td>{getPriorityLabel(t.priority)}</td>
              <td>{getStatusLabel(t.status)}</td>
              <td>
                <button onClick={() => handleEditClick(t.id)}>Edit</button>
                <button onClick={() => onDelete(t.id)}>Delete</button>
              </td>
            </tr>
          )}
          </tbody>
        </table>
      </div>
      <div className="footer">
        <select value={priorityFilter} onChange={(e) => handlePriorityFilter(Number(e.target.value))}>
          <option value="-1">All Priorities</option>
          {PRIORITY_VALUES.map(v => <option value={v.value}>{v.label}</option>)}
        </select>
        <select value={statusFilter} onChange={(e) => handleStatusFilter(Number(e.target.value))}>
          <option value="-1">All Statuses</option>
          {STATUS_VALUES.map(v => <option value={v.value}>{v.label}</option>)}
        </select>
      </div>
    </div>
  );
}
