// vue/story-004-vue/src/components/TaskList.vue
<script setup>
import { ref } from 'vue';

import TaskEdit from './TaskEdit.vue';
import { getPriorityLabel, getStatusLabel, PRIORITY_VALUES, STATUS_VALUES} from '@/helpers/labels';

const props = defineProps(['tasks']);
const emit = defineEmits(['onUpdate', 'onDelete', 'onSort', 'onFilter']);

const priorityFilter = ref(-1);
const statusFilter = ref(-1);
const editId = ref(null);

function handleEditClick(id) {
  editId.value = id;
}

function handleUpdateClick(task) {
  emit('onUpdate', task);
  editId.value = null;
}

function handleCancelClick() {
  editId.value = null;
}

function handleFilter() {
  emit('onFilter', priorityFilter.value, statusFilter.value);
}
</script>

<template>
  <div class="tasklist">
    <div class="body">
      <table>
        <thead>
          <tr>
            <th @click="$emit('onSort', 'id')">ID</th>
            <th @click="$emit('onSort', 'name')">Name</th>
            <th @click="$emit('onSort', 'priority')">Priority</th>
            <th @click="$emit('onSort', 'status')">Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <template v-for="t in props.tasks" :key="t.id">
            <tr v-if="editId === t.id">
              <td colspan="5" class="edit">
                <TaskEdit :tasks="props.tasks" :id="editId" @onUpdate="handleUpdateClick" @onCancel="handleCancelClick" />
              </td>
            </tr>
            <tr v-else>
              <td>{{ t.id }}</td>
              <td>{{ t.name }}</td>
              <td>{{ getPriorityLabel(t.priority) }}</td>
              <td>{{ getStatusLabel(t.status) }}</td>
              <td>
                <button @click="handleEditClick(t.id)">Edit</button>
                <button @click="$emit('onDelete', t.id)">Delete</button>
              </td>
            </tr>
          </template>
        </tbody>
      </table>  
    </div>
    <div class="footer">
      <select v-model="priorityFilter" @change="handleFilter">
        <option :value="-1">All Priorities</option>
        <option v-for="item in PRIORITY_VALUES" :value="item.value">{{ item.label }}</option>
      </select>
      <select v-model="statusFilter" @change="handleFilter">
        <option :value="-1">All Statuses</option>
        <option v-for="item in STATUS_VALUES" :value="item.value">{{ item.label }}</option>
      </select>
    </div>
  </div>
</template>

<style scoped>
.tasklist {
  padding: 10px;
  border: solid 1px #ccc;
}

.body table {
  width: 100%;
  padding: 16px;
}

.body table th {
  cursor: pointer;
}

.body table th, td {
  padding: 8px;
}

.body table thead {
  background-color: #eee;
}

.body table td.edit {
  padding: 0;
}

.footer {
  margin-top: 32px;
  margin-bottom: 16px;
  text-align: center;
}
</style>

// react/story-004-typescript/src/components/TaskList.tsx
import { useState } from 'react';

import TaskEdit from './TaskEdit';
import { getStatusLabel, getPriorityLabel, STATUS_VALUES, PRIORITY_VALUES } from '../helpers/labels';
import type { TaskListProps, Task, PriorityFilter, StatusFilter} from '../types/types';

import './TaskList.css';

export default function TaskList({ tasks, onUpdate, onDelete, onSort, onFilter }: TaskListProps) {
  const [priorityFilter, setPriorityFilter] = useState<PriorityFilter>(-1);
  const [statusFilter, setStatusFilter] = useState<StatusFilter>(-1);
  const [editId, setEditId] = useState<number | null>(null);

  function handleEditClick(id: number) {
    setEditId(id);
  }

  function handleUpdateClick(task: Task) {
    onUpdate(task);
    setEditId(null);
  }

  function handleCancelClick() {
    setEditId(null);
  }

  function handleSortingClick(property: keyof Task) {
    const sorted = [...tasks];

    switch (property) {
      case 'id': sorted.sort((a, b) => a.id - b.id); break;
      case 'name': sorted.sort((a, b) => a.name.localeCompare(b.name)); break;
      case 'priority': sorted.sort((a, b) => a.priority - b.priority); break;
      case 'status': sorted.sort((a, b) => a.status - b.status); break;
      default: break;
    }

    onSort(sorted);
  }

  function handlePriorityFilter(priority: number) {
    priority = Number(priority) ;
    setPriorityFilter(priority as PriorityFilter);
    onFilter(priority as PriorityFilter, statusFilter as StatusFilter);
  }

  function handleStatusFilter(status: number) {
    status = Number(status);
    setStatusFilter(status as StatusFilter);
    onFilter(priorityFilter as PriorityFilter, status as StatusFilter);
  }

  return (
    <div className="TaskList">
      <div className="body">
        <table>
          <thead>
            <tr>
              <th onClick={() => handleSortingClick('id')}>ID</th>
              <th onClick={() => handleSortingClick('name')}>Task</th>
              <th onClick={() => handleSortingClick('priority')}>Priority</th>
              <th onClick={() => handleSortingClick('status')}>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          {tasks.map((t) => editId === t.id ?
            <tr key={t.id}>
              <td colSpan={5} className="edit">
                <TaskEdit tasks={tasks} id={editId} onUpdate={handleUpdateClick} onCancel={handleCancelClick} />
              </td>
            </tr> :
            <tr key={t.id}>
              <td>{t.id}</td>
              <td>{t.name}</td>
              <td>{getPriorityLabel(t.priority)}</td>
              <td>{getStatusLabel(t.status)}</td>
              <td>
                <button onClick={() => handleEditClick(t.id)}>Edit</button>
                <button onClick={() => onDelete(t.id)}>Delete</button>
              </td>
            </tr>
          )}
          </tbody>
        </table>
      </div>
      <div className="footer">
        <select value={priorityFilter} onChange={(e) => handlePriorityFilter(Number(e.target.value))}>
          <option value="-1">All Priorities</option>
          {PRIORITY_VALUES.map(v => <option value={v.value}>{v.label}</option>)}
        </select>
        <select value={statusFilter} onChange={(e) => handleStatusFilter(Number(e.target.value))}>
          <option value="-1">All Statuses</option>
          {STATUS_VALUES.map(v => <option value={v.value}>{v.label}</option>)}
        </select>
      </div>
    </div>
  );
}
