// angular/story-203-angular/src/app/components/task-app/task-app.component.ts
import { inject, Component, ElementRef } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

import { TaskType } from '../../interfaces/task-type.interface';
import { PriorityLabelPipe } from '../../pipes/priority-label.pipe';
import { StatusLabelPipe } from '../../pipes/status-label.pipe';

@Component({
  selector: 'task-app',
  imports: [ReactiveFormsModule, PriorityLabelPipe, StatusLabelPipe],
  templateUrl: './task-app.component.html',
  styleUrl: './task-app.component.css'
})
export class TaskApp {
  nextId = 0;
  allTasks = <TaskType[]>[];

  tasks = <TaskType[]>[];
  task = <TaskType>({id: null, name: '', priority: 0, status: 0});

  inputRef = <ElementRef | null> null;
  name = new FormControl('');
  priority = new FormControl<number>(0);
  status = new FormControl<number>(0);

  priorityFilter = new FormControl<number>(-1);
  statusFilter = new FormControl<number>(-1);

  constructor() {
    this.inputRef = inject(ElementRef);
  }

  filterTasks(priority: number | null = -1, status: number | null = -1) {
    if (priority !== null && priority > -1 && status !== null && status > -1)
      return this.allTasks.filter(t => t.priority === priority && t.status === status);
    else if (priority !== null && priority > -1)
      return this.allTasks.filter(t => t.priority === priority);
    else if (status !== null && status > -1)
      return this.allTasks.filter(t => t.status === status);

    return [...this.allTasks];
  }

  resetTask() {
    this.task = {id: null, name: '', priority: 0, status: 0};
    this.name.setValue('');
    this.priority.setValue(0);
    this.status.setValue(0);
  }

  onKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') this.onUpdateClick();
    if (e.key === 'Escape') this.onEditClick();
  }

  onUpdateClick() {
    if (this.task.id === null) {
      const create: TaskType = {
        id: this.nextId,
        name: this.name.value || '',
        priority: this.priority.value || 0,
        status: this.status.value || 0,
      };

      this.task = create;
      this.allTasks.push(create);
      this.nextId++;
    } else {
      const index: number = this.tasks.findIndex(t => t.id == this.task.id);

      const update: TaskType = {
        id: this.task.id,
        name: this.name.value || '',
        priority: this.priority.value || 0,
        status: this.status.value || 0,
      };

      this.allTasks.splice(index, 1, update);
    }

    this.tasks = [...this.allTasks];
    this.resetTask();
  }

  onEditClick(id: number | null = null) {
    if (this.task.id === null && id !== null) {
      const found = this.tasks.find(t => t.id === id);
      this.task = found || {id: null, name: '', priority: 0, status: 0};
      this.name.setValue(found?.name || this.task.name);
      this.priority.setValue(found?.priority || this.task.priority);
      this.status.setValue(found?.status || this.task.priority);
    } else {
      this.resetTask();
    }

    this.inputRef?.nativeElement.querySelector('#inputRef')?.focus();
  }

  onDeleteClick(id: number | null) {
    this.allTasks = this.allTasks.filter(t => t.id !== id);
    this.tasks = [...this.allTasks];
  }

  onSortingClick(property: string) {
    switch (property) {
      case 'id':
        this.tasks.sort((a: TaskType, b: TaskType) => {
          if (a.id !== null && b.id !== null) return a.id - b.id;
          if (a.id !== null && b.id === null) return 1;
          if (a.id === null && b.id !== null) return -1;
          return 0;
        });
        break;
      case 'name':
        this.tasks.sort((a: TaskType, b: TaskType) => {
          if (a.name > b.name) return 1;
          if (a.name < b.name) return -1;
          return 0;
        });
        break;
      case 'priority':
        this.tasks.sort((a: TaskType, b: TaskType) => a.priority - b.priority);
        break;
      case 'status':
        this.tasks.sort((a: TaskType, b: TaskType) => a.status - b.status);
        break;
    }
  }

  onPriorityFilter() {
    const priority = this.priorityFilter.value;

    this.tasks = this.filterTasks(priority, this.statusFilter.value);
    this.priorityFilter.setValue(priority);
  }

  onStatusFilter() {
    const status = this.statusFilter.value;

    this.tasks = this.filterTasks(this.priorityFilter.value, status);
    this.statusFilter.setValue(status);
  }
}

<div class="task-app">
  <div class="head">
    <input id="inputRef" class="task" placeholder="Enter a task" type="text" [formControl]="name"
      (keydown)="onKeyDown($event)" autofocus />
    <select [formControl]="priority">
      <option [ngValue]="0">Low</option>
      <option [ngValue]="1">Normal</option>
      <option [ngValue]="2">High</option>
      <option [ngValue]="3">Urgent</option>
    </select>
    <select [formControl]="status">
      <option [ngValue]="0">Todo</option>
      <option [ngValue]="1">Doing</option>
      <option [ngValue]="2">Done</option>
    </select>
    <button (click)="onUpdateClick()">@if (task.id === null) { Create } @else { Update }</button>
  </div>
  <div class="body">
    <table>
      <thead>
        <tr>
          <th (click)="onSortingClick('id')">ID</th>
          <th (click)="onSortingClick('name')">Task</th>
          <th (click)="onSortingClick('priority')">Priority</th>
          <th (click)="onSortingClick('status')">Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        @for (t of tasks; track t.id) {
          <tr>
            <td>{{ t.id }}</td>
            <td>{{ t.name }}</td>
            <td>{{ t.priority | priorityLabel }}</td>
            <td>{{ t.status | statusLabel }}</td>
            <td>
              <button (click)="onEditClick(t.id)">{{task.id === t.id ? 'Cancel' : 'Edit'}}</button>
              <button (click)="onDeleteClick(t.id)">Delete</button>
            </td>
          </tr>
        }
      </tbody>
    </table>
  </div>
  <div class="footer">
    <select [formControl]="priorityFilter" (change)="onPriorityFilter()">
      <option [ngValue]="-1">All Priorities</option>
      <option [ngValue]="0">Low</option>
      <option [ngValue]="1">Normal</option>
      <option [ngValue]="2">High</option>
      <option [ngValue]="3">Urgent</option>
    </select>
    <select [formControl]="statusFilter" (change)="onStatusFilter()">
      <option [ngValue]="-1">All Statuses</option>
      <option [ngValue]="0">Todo</option>
      <option [ngValue]="1">Doing</option>
      <option [ngValue]="2">Done</option>
    </select>
  </div>
</div>

// story-002-react/src/components/TaskApp.jsx
import { useState, useRef } from 'react';

import { getStatusLabel, getPriorityLabel } from '../helpers/labels';
import './TaskApp.css';

let nextId = 0;
let allTasks = [];

export default function TaskApp() {
  const [tasks, setTasks] = useState([]);
  const [task, setTask] = useState({ id: null, name: '', priority: 0, status: 0 });
  const [priorityFilter, setPriorityFilter] = useState(-1);
  const [statusFilter, setStatusFilter] = useState(-1);
  const inputRef = useRef(null);

  function filterTasks(priority = -1, status = -1) {
    if (priority > -1 && status > -1)
      return allTasks.filter(t => t.priority === priority && t.status === status);
    else if (priority > -1)
      return allTasks.filter(t => t.priority === priority);
    else if (status > -1)
      return allTasks.filter(t => t.status === status);

    return [...allTasks];
 }

  function resetTask() {
    setTask({ id: null, name: '', priority: 0, status: 0 });
 }

  function handleKeyDown(e) {
    if (e.key === 'Enter') handleUpdateClick();
    if (e.key === 'Escape') handleEditClick();
 }

  function handleUpdateClick() {
    if (task.id === null) {
      const create = { ...task, id: nextId++ };
      setTask(create);
      allTasks.push(create);
   } else {
      const index = allTasks.findIndex(t => t.id === task.id);
      const update = allTasks[index];

      update.name = task.name;
      update.priority = parseInt(task.priority);
      update.status = parseInt(task.status);

      allTasks.splice(index, 1, update);
   }

    setTasks([...allTasks]);
    resetTask();
 }

  function handleEditClick(id = null) {
    if (task.id === null && id !== null) {
      setTask(tasks.find(t => t.id === id));
   } else {
      resetTask();
   }

    inputRef.current.focus();
 }

  function handleDeleteClick(id) {
    allTasks = allTasks.filter(t => t.id !== id);
    setTasks([...allTasks]);
 }

  function handleSortingClick(property) {
    const sorted = [...tasks];

    switch (property) {
      case 'id':
        sorted.sort((a, b) => a.id - b.id);
        break;
      case 'name':
        sorted.sort((a, b) => a.name.localeCompare(b.name));
        break;
      case 'priority':
        sorted.sort((a, b) => a.priority - b.priority);
        break;
      case 'status':
        sorted.sort((a, b) => a.status - b.status);
        break;
   }

    setTasks(sorted);
 }

  function handlePriorityFilter(priority) {
    priority = parseInt(priority);

    setTasks(filterTasks(priority, statusFilter));
    setPriorityFilter(priority);
 }

  function handleStatusFilter(status) {
    status = parseInt(status);

    setTasks(filterTasks(priorityFilter, status));
    setStatusFilter(status);
 }

  return (
    <div className="TaskApp">
      <div className="header">
        <input placeholder="Enter a task" ref={inputRef} value={task.name} onKeyDown={handleKeyDown}
          onChange={e => setTask({...task, name: e.target.value})} autoFocus />
        <select value={task.priority} onChange={e => setTask({...task, priority: parseInt(e.target.value)})}>
          <option value="0">Low</option>
          <option value="1">Normal</option>
          <option value="2">High</option>
          <option value="3">Urgent</option>
        </select>
        <select value={task.status} onChange={e => setTask({...task, status: parseInt(e.target.value)})}>
          <option value="0">Todo</option>
          <option value="1">Doing</option>
          <option value="2">Done</option>
        </select>
        <button onClick={handleUpdateClick}>{task.id === null ? 'Create' : 'Update'}</button>
      </div>
      <div className="body">
        <table>
          <thead>
            <tr>
              <th onClick={() => handleSortingClick('id')}>ID</th>
              <th onClick={() => handleSortingClick('name')}>Task</th>
              <th onClick={() => handleSortingClick('priority')}>Priority</th>
              <th onClick={() => handleSortingClick('status')}>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          {tasks.map((t) =>
            <tr key={t.id}>
              <td>{t.id}</td>
              <td>{t.name}</td>
              <td>{getPriorityLabel(t.priority)}</td>
              <td>{getStatusLabel(t.status)}</td>
              <td>
                <button onClick={() => handleEditClick(t.id)}>{task?.id === t.id ? 'Cancel' : 'Edit'}</button>
                <button onClick={() => handleDeleteClick(t.id)}>Delete</button>
              </td>
            </tr>)}
          </tbody>
        </table>
      </div>
      <div className="footer">
        <select value={priorityFilter} onChange={(e) => handlePriorityFilter(e.target.value)}>
          <option value="-1">All Priorities</option>
          <option value="0">Low</option>
          <option value="1">Normal</option>
          <option value="2">High</option>
          <option value="3">Urgent</option>
        </select>
        <select value={statusFilter} onChange={(e) => handleStatusFilter(e.target.value)}>
          <option value="-1">All Statuses</option>
          <option value="0">Todo</option>
          <option value="1">Doing</option>
          <option value="2">Done</option>
        </select>
      </div>
    </div>
  );
}
