// angular/story-202-angular/src/app/components/task-app/task-app.component.ts
import { inject, Component, ElementRef, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

interface TaskType {
  id: number | null;
  name: string;
}

@Component({
  selector: 'task-app',
  imports: [ReactiveFormsModule],
  templateUrl: './task-app.component.html',
  styleUrl: './task-app.component.css'
})
export class TaskApp {
  nextId = signal(0);
  tasks = signal<TaskType[]>([]);
  task = signal<TaskType>({ id: null, name: '' });

  inputRef = <ElementRef | null> null;
  name = new FormControl('');

  constructor() {
    this.inputRef = inject(ElementRef);
  }

  onKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' && this.task().id === null) this.onCreateClick();
    if (e.key === 'Enter' && this.task().id !== null) this.onUpdateClick();
    if (e.key === 'Escape') this.onCancelClick();
  }

  onCreateClick() {
    this.tasks.update(current => [ ...current, {
      id: this.nextId(),
      name: this.name.value || '',
    }]);

    this.nextId.update(v => v + 1);
    this.name.setValue('');
  }

  onUpdateClick() {
    this.tasks.update(current => current.map(t => {
      if (t.id === this.task().id) {
        return {
          id: this.task().id,
          name: this.name.value || '',
        };
      } else {
        return t;
      }
    }));

    this.task.set({ id: null, name: '' });
    this.name.setValue('');
  }

  onEditClick(id: number | null) {
    const found = this.tasks().find(t => t.id === id);

    if (found) {
      this.task.set(found);
      this.name.setValue(found.name);
    }

    this.inputRef?.nativeElement.querySelector('#inputRef')?.focus();
  }

  onCancelClick() {
    this.task.set({ id: null, name: '' });
    this.name.setValue('');
  }

  onDeleteClick(id: number | null) {
    this.tasks.update(current => [ ...current.filter(t => t.id !== id) ]);
  }
}

<div class="task-app">
  <div class="head">
    <input id="inputRef" class="task" placeholder="Enter a task" type="text" [formControl]="name"
      (keydown)="onKeyDown($event)" autofocus />

    @if (task().id === null) {
      <button (click)="onCreateClick()">Create</button>
    } @else {
      <button (click)="onUpdateClick()">Update</button>
    }
  </div>
  <div class="body">
    <ol>
      @for (t of tasks(); track t.id) {
        <li>
          <span class="task">{{ t.name }}</span>
          @if (task().id === t.id) {
            <button (click)="onCancelClick()">Cancel</button>
          } @else {
            <button (click)="onEditClick(t.id)">Edit</button>
          }
          <button (click)="onDeleteClick(t.id)">Delete</button>
        </li>
      }
    </ol>
  </div>
</div>

// react/story-001-react/src/components/TaskApp.jsx

import { useState, useRef } from 'react';

import './TaskApp.css';

let nextId = 0;

export default function TaskApp() {
  const [tasks, setTasks] = useState([]);
  const [task, setTask] = useState(null);
  const [name, setName] = useState('');
  const inputRef = useRef(null);

  function handleKeyDown(e) {
    if (e.key === 'Enter') handleUpdateClick();
    if (e.key === 'Escape') handleEditClick();
  }

  function handleUpdateClick() {
    if (!name.trim()) return;

    if (task === null) {
      const newTask = {
        id: nextId++,
        name: name.trim(),
        status: 'Todo',
        priority: 'Normal',
      };
      setTasks([...tasks, newTask]);
    } else {
      setTasks(tasks.map(t => (t.id === task.id ? { ...t, name: name.trim() } : t)));
      setTask(null);
    }

    setName('');
    inputRef.current.focus();
  }

  function handleEditClick(id = null) {
    if (task === null && id !== null) {
      const found = tasks.find(t => t.id === id);
      setTask(found);
      setName(found.name ?? null);
    } else {
      setTask(null);
      setName('');
    }

    inputRef.current.focus();
  }

  function handleDeleteClick(id) {
    setTasks(tasks.filter(t => t.id !== id));
  }

  return (
    <div className="TaskApp">
      <div className="head">
        <input className="task" placeholder="Enter a task" ref={inputRef} value={name}
          onChange={e => setName(e.target.value)} onKeyDown={handleKeyDown} autoFocus />
        <button onClick={handleUpdateClick}>{task === null ? 'Create' : 'Update'}</button>
      </div>
      <div className="body">
        <ol>
          {tasks.map((t) =>
            <li key={t.id}>
              <span className="task">{t.name}</span>
              <button onClick={() => handleEditClick(t.id)}>{task?.id === t.id ? 'Cancel' : 'Edit'}</button>
              <button onClick={() => handleDeleteClick(t.id)}>Delete</button>
            </li>)}
        </ol>
      </div>
    </div>
  );
}
