// story-003-react/src/components/TaskEdit.jsx
import { useState } from 'react';

import './TaskEdit.css';

export default function TaskEdit({ tasks, id, onUpdate, onCancel }) {
  const [task, setTask] = useState({ ...tasks.find(t => t.id === id) });

  function handleKeyDown(e) {
    if (e.key === 'Enter') handleUpdateClick();
    if (e.key === 'Escape') onCancel();
  }

  function handleUpdateClick() {
    onUpdate({
      id: task.id,
      name: task.name,
      priority: parseInt(task.priority),
      status: parseInt(task.status),
    });
  }

  return (
    <div className="taskedit">
      <input placeholder="Enter a task" value={task.name} onKeyDown={handleKeyDown}
        onChange={e => setTask({...task, name: e.target.value})} autoFocus />
      <select value={task.priority} onChange={e => setTask({...task, priority: parseInt(e.target.value)})}>
        <option value="0">Low</option>
        <option value="1">Normal</option>
        <option value="2">High</option>
        <option value="3">Urgent</option>
      </select>
      <select value={task.status} onChange={e => setTask({...task, status: parseInt(e.target.value)})}>
        <option value="0">Todo</option>
        <option value="1">Doing</option>
        <option value="2">Done</option>
      </select>
      <button onClick={handleUpdateClick}>Update</button>
      <button onClick={onCancel}>Cancel</button>
    </div>
  );
}

// angular/story-204-angular/src/app/components/task-edit/task-edit.component.ts
import { Component, input, output, effect } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

import { TaskType } from '../../interfaces/task-type.interface';

@Component({
  selector: 'task-edit',
  imports: [ReactiveFormsModule],
  templateUrl: './task-edit.component.html',
  styleUrl: './task-edit.component.css'
})
export class TaskEdit {
  task = input<TaskType>({ id: null, name: '', priority: 0, status: 0 });
  onUpdate = output<TaskType>();
  onCancel = output();

  name = new FormControl('');
  priority = new FormControl<number>(0);
  status = new FormControl<number>(0);

  constructor() {
    effect(() => {
      this.name.setValue(this.task().name);
      this.priority.setValue(this.task().priority);
      this.status.setValue(this.task().status);
    })
  }

  handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') this.handleUpdateClick();
    if (e.key === 'Escape') this.handleCancelClick();
  }

  handleUpdateClick() {
    this.onUpdate.emit({
      id: this.task().id,
      name: this.name.value || '',
      priority: this.priority.value || 0,
      status: this.status.value || 0,
    });
  }

  handleCancelClick() {
    this.onCancel.emit();
  }
}

<div class="task-edit">
  <input placeholder="Enter a task" [formControl]="name" (keydown)="handleKeyDown($event)" autofocus />
  <select [formControl]="priority">
    <option [ngValue]="0">Low</option>
    <option [ngValue]="1">Normal</option>
    <option [ngValue]="2">High</option>
    <option [ngValue]="3">Urgent</option>
  </select>
  <select [formControl]="status">
    <option [ngValue]="0">Todo</option>
    <option [ngValue]="1">Doing</option>
    <option [ngValue]="2">Done</option>
  </select>
  <button (click)="handleUpdateClick()">Update</button>
  <button (click)="handleCancelClick()">Cancel</button>
</div>
