// vue/story-104-vue/src/components/TaskApp.vue
<script setup>
import { ref } from 'vue';

import TaskCreate from './TaskCreate.vue';
import TaskList from './TaskList.vue';

let allTasks = [];
let nextId = ref(0);
let tasks = ref([]);

function refreshAllTasks(t) {
  allTasks = [...t];
}

function handleCreateTask(task) {
  tasks.value = [...tasks.value, task];
  nextId.value++;
  refreshAllTasks(tasks.value);
}

function handleUpdateTask(task) {
  allTasks = allTasks.map((t) => {
    if (t.id === task.id) {
      return task;
    } else {
      return t;
    }
  });

  const _tasks = tasks.value.map(t => {
    if (t.id === task.id) {
      return task;
    } else {
      return t;
    }
  });

  tasks.value = _tasks;
}

function handleDeleteTask(id) {
  const _tasks = [...tasks.value.filter(t => t.id !== id)];
  tasks.value = _tasks;
  refreshAllTasks(_tasks);
}

function handleSort(property) {
  switch (property) {
    case 'id':
      tasks.value.sort((a, b) => a.id - b.id);
      break;
    case 'name':
      tasks.value.sort((a, b) => a.name.localeCompare(b.name));
      break;
    case 'priority':
      tasks.value.sort((a, b) => a.priority - b.priority);
      break;
    case 'status':
      tasks.value.sort((a, b) => a.status - b.status);
      break;
  }
}

function handleFilter(priority = -1, status = -1) {
  if (priority > -1 && status > -1) {
    tasks.value = [...allTasks.filter(t => t.priority === priority && t.status === status)];
  } else if (priority > -1) {
    tasks.value = [...allTasks.filter(t => t.priority === priority)];
  } else if (status > -1) {
    tasks.value = [...allTasks.filter(t => t.status === status)];
  } else {
    tasks.value = [...allTasks];
  }
}
</script>

<template>
  <div class="taskapp">
    <TaskCreate :nextId="nextId" @onCreate="handleCreateTask" />
    <TaskList :tasks="tasks" @onUpdate="handleUpdateTask" @onDelete="handleDeleteTask"
      @onSort="handleSort" @onFilter="handleFilter" />
  </div>
</template>

<style scoped>
.taskapp {
  margin: 0;
}
</style>

// angular/story-204-angular/src/app/components/task-app/task-app.component.ts
import { Component } from '@angular/core';

import { TaskType } from '../../interfaces/task-type.interface';
import { FilterType } from '../../interfaces/filter-type.interface';
import { TaskCreate } from '../task-create/task-create.component';
import { TaskList } from '../task-list/task-list.component';

@Component({
  selector: 'task-app',
  imports: [TaskCreate, TaskList],
  templateUrl: './task-app.component.html',
  styleUrl: './task-app.component.css'
})
export class TaskApp {
  nextId = 0;
  allTasks = <TaskType[]>[];
  tasks = <TaskType[]>[];

  refreshAllTasks(t: TaskType[]) {
    this.allTasks = [...t];
  }

  handleCreateTask(task: TaskType) {
    this.tasks.push(task);
    this.nextId++;
    this.refreshAllTasks(this.tasks);
  }

  handleUpdateTask(task: TaskType) {
    this.allTasks = this.allTasks.map((t: TaskType) => {
      if (t.id === task.id) {
        return task;
      } else {
        return t;
      }
    });

    const _tasks = this.tasks.map((t: TaskType) => {
      if (t.id === task.id) {
        return task;
      } else {
        return t;
      }
    });

    this.tasks = _tasks;
  }

  handleDeleteTask(id: number | null) {
    const _tasks = [...this.tasks.filter((t: TaskType) => t.id !== id)];
    this.tasks = _tasks;
    this.refreshAllTasks(_tasks);
  }

  handleSort(property: string) {
    switch (property) {
      case 'id':
        this.tasks.sort((a: TaskType, b: TaskType) => {
          if (a.id !== null && b.id !== null) return a.id - b.id;
          if (a.id !== null && b.id === null) return 1;
          if (a.id === null && b.id !== null) return -1;
          return 0;
        });
        break;
      case 'name':
        this.tasks.sort((a: TaskType, b: TaskType) => {
          if (a.name > b.name) return 1;
          if (a.name < b.name) return -1;
          return 0;
        });
        break;
      case 'priority':
        this.tasks.sort((a: TaskType, b: TaskType) => a.priority - b.priority);
        break;
      case 'status':
        this.tasks.sort((a: TaskType, b: TaskType) => a.status - b.status);
        break;
    }
  }

  handleFilter(filter: FilterType) {
    if (filter.priority > -1 && filter.status > -1) {
      this.tasks = [...this.allTasks.filter((t: TaskType) => t.priority === filter.priority && t.status === filter.status)];
    } else if (filter.priority > -1) {
      this.tasks = [...this.allTasks.filter((t: TaskType) => t.priority === filter.priority)];
    } else if (filter.status > -1) {
      this.tasks = [...this.allTasks.filter((t: TaskType) => t.status === filter.status)];
    } else {
      this.tasks = [...this.allTasks];
    }
  }
}

<div class="task-app">
  <task-create [nextId]="nextId"
    (onCreate)="handleCreateTask($event)" />
  <task-list [tasks]="tasks"
    (onUpdate)="handleUpdateTask($event)" (onDelete)="handleDeleteTask($event)"
    (onSort)="handleSort($event)" (onFilter)="handleFilter($event)" />
</div>
